### ISSUE TITLE
how to use the function "annulusmap"?

### ISSUE THREAD

**Issue by sirelays** [tobydriscoll/sc-toolbox#15]
Dear tobydriscoll

thank you very much for  your contribution to the SC mapping.
now I use your code of version 3.11. when I run the dctests.m, there are always the bug displayed in my computer about the functions annulusmap. can you tell the detailed usage?
thank you very much.

**Comment by alfaheryudono** [comment]
By quickly taking a look at the codes, it seems to me that your problem can be 
temporarily fixed with the following steps:

1. Edit the following file: @annulusmap/private/qinit.m 
   by adding the following command in line 10:
   import sctool.gaussj
   
   For some reason qinit.m can't access gaussj.m function.
   
2. The command annulusmap in 2014 seems to accept outerpolygon and innerpolygon as 
    polygon objects directly instead of dscpolygons object as in the older version. 
    For example, in example 5 in dctests.m, you instead execute the commands as the following:
   
   z0 = [1+1i 4+1i 4+4*1i 1+4*1i];
   z1 = [2.75+1.5*1i 3.25+3.25*1i 1.5+3*1i];
   p0 = polygon(z0); %Outer Polygon
   p1 = polygon(z1); %Inner Polygon

   f = annulusmap(p0,p1)
   plot(f)
   
So far, this works for me. See if that works for you.

**Comment by sirelays** [comment]
thank you for your comments, which is meaningful for me.
But ,when I run the code "/tests/dctests.m", the error is also existing.
such as "**

> Not enough input arguments.
> 
> Error in annulusmap (line 29)
>             map.boundary = { outerPolygon, innerPolygon };
> 
> Error in dctests (line 46)
> f = annulusmap(rgn)

**"
I donot know the reason. please ……

**Comment by sirelays** [comment]
found the wrong codes (dscpolygons.m), thank you very much
